### ISSUE TITLE
Parameter to kernel function

### ISSUE THREAD

**Issue by Peder2911** [prio-data/views_transformation_library#12]
To be able to include @jimdale 's awesome new spatial lag functions, we need to wrap his functions in a function that allows ViEWSer to call them with simple parameters (str, int, float). This essentially means that we need a function that lets you specify the spatial lag kernel in terms of integers, floats and / or strings

**Comment by Peder2911** [comment]
An example of a simple function that creates a kernel from two integers is:
```
lambda x,y: np.ones((x,y))
```
It would of course be interesting with some more excotic kernels, instead of just flat ones, but this might be a good place to start.

**Comment by jimdale** [comment]
the kernel needs to have a hole at the central cell though, so we need something a little more complex

**Comment by Peder2911** [comment]
Fixed in a55e5fd I think @jimdale, feel free to reopen if we didn't?
