### ISSUE TITLE
Spatial lag functions missing docstrings

### ISSUE THREAD

**Issue by jimdale** [prio-data/views_transformation_library#16]
spatial.lag and spatial.treelag currently have no docstrings, because they are wrapped, and the wrapper has no doctoring.

**Comment by Peder2911** [comment]
Was this resolved with recent PRs @jimdale ?

**Comment by Peder2911** [comment]
What is the status of this @jimdale, solved?

**Comment by jimdale** [comment]
Yes, the spatial lag functions now have reasonably useful docstrings

**Comment by Peder2911** [comment]
Cool! Closing.
